name: Suggest a place
description: Share a spot you liked that would help OSS Europe attendees
title: "[Place] <name of the place>"
labels: ["suggestion"]
assignees: []
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: e.g., Pancakehouse Upstairs
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options: [food, coffee, drinks, dessert]
    validations:
      required: true

  - type: input
    id: neighborhood
    attributes:
      label: Neighborhood
      placeholder: e.g., Centrum, De Pijp, Jordaan

  - type: input
    id: address
    attributes:
      label: Address
      placeholder: street, postal code, city
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      placeholder: official site or Google Maps URL
    validations:
      required: true

  - type: input
    id: from_rai
    attributes:
      label: From RAI
      placeholder: ~X min by tram | metro | walk

  - type: textarea
    id: why_good
    attributes:
      label: Why it is good
      description: One or two plain lines on what makes it worth a stop.
      placeholder: quick, practical reason

  - type: input
    id: dietary
    attributes:
      label: Dietary notes
      placeholder: vegan | veg-friendly | gluten-free | n/a

  - type: textarea
    id: tips
    attributes:
      label: Tips
      description: reservations? small room? good for groups? best time to go?
      placeholder: any quick tips to help visitors
